# Generated by Django 4.0.4 on 2022-05-17 10:55

from django.db import migrations, models
import django.db.models.deletion
import prod.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, null=True)),
                ('code', models.CharField(default=prod.models.codegenerator, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50)),
                ('name', models.CharField(default='name', max_length=16)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, null=True)),
                ('code', models.CharField(default=prod.models.codegenerator, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(default='name', max_length=16)),
                ('describe', models.CharField(default='describe', max_length=25, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, null=True)),
                ('content', models.TextField()),
                ('host', models.CharField(max_length=50, unique=True)),
                ('rating', models.IntegerField()),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.CharField(default='1', max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.product')),
            ],
        ),
    ]
