# Generated by Django 4.0.4 on 2022-05-19 09:22

from django.db import migrations, models
import prod.models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='prod/images/prod.png', upload_to='prod/images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default=prod.models.codegenerator, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=prod.models.codegenerator, max_length=8, unique=True),
        ),
    ]
