# Generated by Django 4.0.4 on 2022-05-19 09:28

from django.db import migrations, models
import prod.models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_product_image_alter_category_code_alter_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default=prod.models.codegenerator, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=prod.models.codegenerator, max_length=8, unique=True),
        ),
    ]
