# Generated by Django 4.0.4 on 2022-05-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0003_remove_product_image_alter_category_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='code',
        ),
        migrations.RemoveField(
            model_name='category',
            name='host',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='host',
        ),
        migrations.RemoveField(
            model_name='review',
            name='host',
        ),
    ]
